# Continuous Integration Workflow
# --------------------------------
# This workflow automatically runs tests and checks when:
# - Code is pushed to the "master" or "dev" branches.
# - A pull request is created for the "master" or "dev" branches.
#
# What this workflow does:
# 1. Gets the latest code from the repository.
# 2. Sets up Node.js (version 22.x) and the pnpm package manager.
# 3. Installs all the project dependencies.
# 4. Checks the code for formatting and style issues (linting).
# 5. Runs tests to ensure the code works correctly.
#
# Notes:
# - The `DATABASE_URL` is a secret used for connecting to the database during tests.

name: Continuous Integration

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL}} 

    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm lint



        

# Here are the tools we use in this pipeline:
  
# Vitest: Tests our code and checks if everything works.
# React Testing Library (RTL): Tests our React components to ensure they behave correctly.
# Jest-DOM: Makes testing the user interface easier.
# ESLint: Checks our code for mistakes and makes sure it looks clean.
# Vercel: Deploys our app online for everyone to access."
